site_name: AI Development Practices Guide
site_description: A guide to best practices and anti-patterns in AI development
site_author: AI Development Team
repo_url: https://github.com/Cprime-Artificial-Intelligence/ai-dev-practices-guide
repo_name: ai-dev-practices-guide

theme:
  name: material
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy
  extra_css:
    - assets/stylesheets/custom.css

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

plugins:
  - search
  - include_dir_to_nav:
      file_name_as_title: true  # Use filenames as titles first
      sort_file: true
      sort_directory: true
      flat: false  # Keep subdirectories as sections
      recurse: true  # Recursively scan directories
      include_empty_dir: false


nav:
  - Home: index.md
  - Overview: overview
  - Best Practices: best-practices
  - Anti-Patterns: antipatterns
