site_name: AI Development Practices Guide
site_description: A guide to best practices and anti-patterns in AI development
site_author: AI Development Team
repo_url: https://github.com/aaronsb/ai-dev-practices-guide
repo_name: ai-dev-practices-guide

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed
  - pymdownx.tasklist
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Best Practices:
    - best-practices/index.md
    - Cyclomatic Complexity: best-practices/cyclomatic-complexity.md
    - Factory Pattern: best-practices/factory-pattern.md
  - Anti-Patterns:
    - antipatterns/index.md
    - Library Reinvention: antipatterns/library-reinvention.md
    - Premature Architecture: antipatterns/premature-architecture.md
    - Purpose Drift: antipatterns/purpose-drift.md
    - Separation of Concerns: antipatterns/separation-of-concerns.md
    - Test Driven Design: antipatterns/test-driven-design.md
